export type ClientStatus = "active" | "expiring" | "due_tomorrow" | "inactive";

export type Client = {
  id: string;
  clientId: string;
  name: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  clientType: "Individual" | "Corporate";
  tier: "Premium Client" | "Standard";
  status: ClientStatus;
  coordinator: string;
  branch: string;
  source: string;
  joinedDate: string;
  vip: boolean;
  patientCount: number;
  activeServices: number;
  activeDuties: number;
  totalDuties: number;
  primaryService: string;
  primaryServiceStart: string;
  primaryServiceShift?: string;
  primaryServiceRate?: string;
  primaryServiceMonthly?: string;
  staffName: string;
  staffRole: string;
  staffRating?: number;
  staffAttendance?: number;
  renewalDate: string;
  renewalInDays: number;
  outstanding: number;
  outstandingDueDays?: number;
  satisfaction: number;
  totalBilling?: number;
  amountCollected?: number;
};

export const CLIENT_STATUS_LABELS: Record<ClientStatus, string> = {
  active: "Active",
  expiring: "Expiring",
  due_tomorrow: "Due Tomorrow",
  inactive: "Inactive",
};

export const CLIENT_STATUS_STYLES: Record<ClientStatus, string> = {
  active: "bg-emerald-100 text-emerald-800",
  expiring: "bg-amber-100 text-amber-800",
  due_tomorrow: "bg-red-100 text-red-800",
  inactive: "bg-gray-100 text-gray-700",
};

export const CLIENT_KPI = [
  { title: "Total Active Clients", value: "1,248", trend: "↑ 12.6%", up: true },
  { title: "Active Services", value: "832", trend: "↑ 9.6%", up: true },
  { title: "New Clients This Month", value: "124", trend: "↑ 18.7%", up: true },
  { title: "Expiring Services", value: "47", trend: "↓ 8.5%", up: false },
  { title: "Outstanding Dues", value: "₹18,45,000", trend: "↑ 6.2%", up: true },
  { title: "High-Risk Clients", value: "23", trend: "↑ 15.0%", up: true },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: "1",
    clientId: "CL-1258",
    name: "Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma@email.com",
    address: "Sector 45, Gurgaon, Haryana",
    city: "Gurgaon",
    clientType: "Individual",
    tier: "Premium Client",
    status: "active",
    coordinator: "Neha Patel",
    branch: "Gurgaon",
    source: "Referral",
    joinedDate: "15 May 2023",
    vip: true,
    patientCount: 2,
    activeServices: 2,
    activeDuties: 4,
    totalDuties: 18,
    primaryService: "ICU Nurse (12H)",
    primaryServiceStart: "Started 12 May 2025",
    primaryServiceShift: "12 Hours",
    primaryServiceRate: "₹1,800 / day",
    primaryServiceMonthly: "₹54,000 / month",
    staffName: "Priya Singh",
    staffRole: "ICU Nurse",
    staffRating: 4.8,
    staffAttendance: 96,
    renewalDate: "15 Jun 2026",
    renewalInDays: 34,
    outstanding: 12000,
    outstandingDueDays: 13,
    satisfaction: 4.8,
    totalBilling: 245000,
    amountCollected: 233000,
  },
  {
    id: "2",
    clientId: "CL-1259",
    name: "Anita Verma",
    phone: "+91 98123 45678",
    email: "anita.v@email.com",
    address: "Sector 62, Noida",
    city: "Noida",
    clientType: "Individual",
    tier: "Standard",
    status: "expiring",
    coordinator: "Rahul Sharma",
    branch: "Noida (HQ)",
    source: "Website",
    joinedDate: "3 Jan 2024",
    vip: false,
    patientCount: 1,
    activeServices: 1,
    activeDuties: 2,
    totalDuties: 8,
    primaryService: "Attendant (24H)",
    primaryServiceStart: "Started 1 Apr 2025",
    staffName: "Suresh Kumar",
    staffRole: "Attendant",
    staffRating: 4.5,
    staffAttendance: 92,
    renewalDate: "28 May 2025",
    renewalInDays: 16,
    outstanding: 8500,
    outstandingDueDays: 5,
    satisfaction: 4.2,
    totalBilling: 98000,
    amountCollected: 89500,
  },
  {
    id: "3",
    clientId: "CL-1260",
    name: "Vikram Malhotra",
    phone: "+91 99887 76655",
    email: "vikram.m@email.com",
    address: "Defence Colony, Delhi",
    city: "Delhi",
    clientType: "Corporate",
    tier: "Premium Client",
    status: "due_tomorrow",
    coordinator: "Neha Patel",
    branch: "Delhi",
    source: "Partner",
    joinedDate: "20 Aug 2022",
    vip: true,
    patientCount: 3,
    activeServices: 3,
    activeDuties: 6,
    totalDuties: 42,
    primaryService: "Physiotherapist",
    primaryServiceStart: "Started 10 Mar 2025",
    staffName: "Dr. Meera Joshi",
    staffRole: "Physiotherapist",
    staffRating: 4.9,
    staffAttendance: 98,
    renewalDate: "30 May 2025",
    renewalInDays: 1,
    outstanding: 24500,
    outstandingDueDays: 1,
    satisfaction: 4.9,
    totalBilling: 520000,
    amountCollected: 495500,
  },
  {
    id: "4",
    clientId: "CL-1261",
    name: "Sunita Devi",
    phone: "+91 91234 56789",
    email: "sunita.d@email.com",
    address: "Faridabad Sector 21",
    city: "Faridabad",
    clientType: "Individual",
    tier: "Standard",
    status: "active",
    coordinator: "Amit Singh",
    branch: "Faridabad",
    source: "Justdial",
    joinedDate: "12 Nov 2024",
    vip: false,
    patientCount: 1,
    activeServices: 1,
    activeDuties: 1,
    totalDuties: 4,
    primaryService: "Baby Care (12H)",
    primaryServiceStart: "Started 5 May 2025",
    staffName: "Kavita Rani",
    staffRole: "Baby Care",
    staffRating: 4.6,
    staffAttendance: 94,
    renewalDate: "5 Jul 2025",
    renewalInDays: 54,
    outstanding: 0,
    satisfaction: 4.7,
    totalBilling: 42000,
    amountCollected: 42000,
  },
  {
    id: "5",
    clientId: "CL-1262",
    name: "Rajesh Gupta",
    phone: "+91 98700 11223",
    email: "rajesh.g@email.com",
    address: "DLF Phase 3, Gurgaon",
    city: "Gurgaon",
    clientType: "Individual",
    tier: "Premium Client",
    status: "active",
    coordinator: "Neha Patel",
    branch: "Gurgaon",
    source: "Referral",
    joinedDate: "8 Feb 2023",
    vip: true,
    patientCount: 2,
    activeServices: 2,
    activeDuties: 3,
    totalDuties: 22,
    primaryService: "ICU Nurse (24H)",
    primaryServiceStart: "Started 20 Jan 2025",
    staffName: "Anjali Mehta",
    staffRole: "ICU Nurse",
    staffRating: 4.7,
    staffAttendance: 95,
    renewalDate: "20 Aug 2025",
    renewalInDays: 100,
    outstanding: 18000,
    outstandingDueDays: 20,
    satisfaction: 4.5,
    totalBilling: 312000,
    amountCollected: 294000,
  },
  {
    id: "6",
    clientId: "CL-1263",
    name: "Meera Kapoor",
    phone: "+91 98111 22334",
    email: "meera.k@email.com",
    address: "Greater Noida West",
    city: "Noida",
    clientType: "Individual",
    tier: "Standard",
    status: "expiring",
    coordinator: "Rahul Sharma",
    branch: "Noida (HQ)",
    source: "Google Ads",
    joinedDate: "1 Jun 2024",
    vip: false,
    patientCount: 1,
    activeServices: 1,
    activeDuties: 2,
    totalDuties: 6,
    primaryService: "Elder Care (12H)",
    primaryServiceStart: "Started 15 Apr 2025",
    staffName: "Ramesh Yadav",
    staffRole: "Elder Care",
    staffRating: 4.3,
    staffAttendance: 88,
    renewalDate: "2 Jun 2025",
    renewalInDays: 21,
    outstanding: 6200,
    satisfaction: 4.0,
    totalBilling: 68000,
    amountCollected: 61800,
  },
  {
    id: "7",
    clientId: "CL-1264",
    name: "Arjun Reddy",
    phone: "+91 99000 88776",
    email: "arjun.r@email.com",
    address: "South Extension, Delhi",
    city: "Delhi",
    clientType: "Corporate",
    tier: "Premium Client",
    status: "active",
    coordinator: "Amit Singh",
    branch: "Delhi",
    source: "Website",
    joinedDate: "14 Mar 2021",
    vip: true,
    patientCount: 4,
    activeServices: 4,
    activeDuties: 8,
    totalDuties: 56,
    primaryService: "ICU Nurse (12H)",
    primaryServiceStart: "Started 1 Jan 2025",
    staffName: "Multiple",
    staffRole: "ICU Nurse",
    renewalDate: "1 Jan 2026",
    renewalInDays: 234,
    outstanding: 45000,
    outstandingDueDays: 45,
    satisfaction: 4.6,
    totalBilling: 890000,
    amountCollected: 845000,
  },
  {
    id: "8",
    clientId: "CL-1265",
    name: "Pooja Nair",
    phone: "+91 97654 32109",
    email: "pooja.n@email.com",
    address: "Sector 15, Gurgaon",
    city: "Gurgaon",
    clientType: "Individual",
    tier: "Standard",
    status: "inactive",
    coordinator: "Neha Patel",
    branch: "Gurgaon",
    source: "Phone Call",
    joinedDate: "22 Sep 2023",
    vip: false,
    patientCount: 0,
    activeServices: 0,
    activeDuties: 0,
    totalDuties: 12,
    primaryService: "—",
    primaryServiceStart: "—",
    staffName: "—",
    staffRole: "—",
    renewalDate: "—",
    renewalInDays: 0,
    outstanding: 0,
    satisfaction: 3.8,
    totalBilling: 156000,
    amountCollected: 156000,
  },
];

export const DEFAULT_CLIENT_STAFF = [
  { name: "Priya Singh", role: "ICU Nurse", rating: 4.8, attendance: 96, replacements: 0 },
  { name: "Dr. Meera Joshi", role: "Physiotherapist", rating: 4.9, attendance: 98, replacements: 1 },
  { name: "Suresh Kumar", role: "Attendant", rating: 4.5, attendance: 92, replacements: 2 },
];

export const DEFAULT_CLIENT_SERVICES = [
  { name: "ICU Nurse (24 Hours)", start: "12 May 2025", status: "Active" as const },
  { name: "Attendant (24 Hours)", start: "15 May 2025", status: "Active" as const },
];

export const DEFAULT_CLIENT_ACTIVITIES = [
  { title: "Payment Received", detail: "₹25,000 via UPI", at: "May 11, 2025 · 10:30 AM" },
  { title: "Service Extended", detail: "ICU Nurse extended by 30 days", at: "May 10, 2025 · 03:15 PM" },
  { title: "Patient Added", detail: "Mrs. Sharma added as patient", at: "May 8, 2025 · 11:00 AM" },
];
